# docker-compose.yml
# ----------------------------------------------------------------------------
# Composes Docker containers and volumes to a runnable application
# ----------------------------------------------------------------------------
#
---
services:

  backend:
    image: docker.cloudtrain.aws.msgoat.eu/cloudtrain/cnj-config-backend-quarkus:latest
    ports:
      - "38080:8080"
    environment:
      DOCKER_JAVA_OPTS: "-Xms1G -Xmx1G"
      CLOUDTRAIN_CONFIG_STRINGVALUE: "environmentVariables"
      CLOUDTRAIN_CONFIG_NUMERICVALUE: "456"
